### ISSUE TITLE
infrastructure: db schema and forms

### ISSUE THREAD

**Issue by dimofte** [tbbooher/journal#12]
If we’re going to use other data structures besides the daily entries (and have other forms), it would probably make sense to install and use the trio `collections2`, `simple-schema` and `autoform` asap.
We'll then have better data validation and forms (ditching the long html and using a short template with autoform helpers instead)

**Comment by tbbooher** [comment]
Great. Let's do it.

**Comment by tbbooher** [comment]
https://github.com/aldeed/meteor-collection2 looks great

let's elevate this to the top priority before the database needs a lot of cleanup. just fyi -- i have invalid data in the system now in the sense that there are duplicate dates. i'm going to elevate the priority of that as well.

**Comment by tbbooher** [comment]
i'm implementing now
